# Generated by Django 5.0.7 on 2024-07-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assign',
            unique_together=set(),
        ),
    ]
