# Generated by Django 5.1 on 2024-08-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='deccription',
            new_name='description',
        ),
    ]
