# Generated by Django 5.1 on 2024-08-27 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.file'),
        ),
    ]
