# Generated by Django 5.1 on 2024-08-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_currency_currencyvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='pricing',
        ),
        migrations.AddField(
            model_name='currency',
            name='pricing',
            field=models.ManyToManyField(to='app.pricing'),
        ),
    ]
