# Generated by Django 5.1 on 2024-08-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_currency_pricing_currency_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='pricing',
            field=models.ManyToManyField(blank=True, null=True, to='app.pricing'),
        ),
    ]
