# Generated by Django 5.1 on 2024-08-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_currency_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='pricing',
        ),
        migrations.AddField(
            model_name='pricing',
            name='currency',
            field=models.ManyToManyField(blank=True, null=True, to='app.currency'),
        ),
    ]
