# Generated by Django 5.1 on 2024-09-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_currency_pricing_pricing_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='currency',
        ),
        migrations.AddField(
            model_name='pricing',
            name='aed_conversion_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='egp_conversion_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='try_conversion_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CurrencyValue',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
