# Generated by Django 5.1 on 2024-09-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_pricing_currency_pricing_aed_conversion_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='aed_conversion_rate',
            new_name='eur_to_ae',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='egp_conversion_rate',
            new_name='eur_to_egp',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='try_conversion_rate',
            new_name='eur_to_rs',
        ),
        migrations.AddField(
            model_name='pricing',
            name='eur_to_strlini',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='eur_to_tr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='eur_to_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='usd_to_ae',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='usd_to_egp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='usd_to_eur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='usd_to_rs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='usd_to_strlini',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='usd_to_tr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
