# Generated by Django 5.1 on 2024-09-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_aed_conversion_rate_pricing_eur_to_ae_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='ae_buy_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='ae_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='ae_profit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='eg_buy_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='eg_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='eg_profit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='tr_buy_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='tr_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='tr_profit',
            field=models.FloatField(),
        ),
    ]
