# Generated by Django 5.1 on 2024-09-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_pricing_ae_buy_price_alter_pricing_ae_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='currency_entry',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR')], max_length=3, null=True),
        ),
    ]
