# Generated by Django 5.1 on 2024-09-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_pricing_currency_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='currency_entry',
        ),
    ]
