# Generated by Django 5.1 on 2024-09-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_pricing_currency_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='eur_to_ae',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='eur_to_egp',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='eur_to_rs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='eur_to_strlini',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='eur_to_tr',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='eur_to_usd',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='usd_to_ae',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='usd_to_egp',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='usd_to_eur',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='usd_to_rs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='usd_to_strlini',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='usd_to_tr',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
