# Generated by Django 5.1 on 2024-09-01 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_purchasebill_salesbill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebill',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='salesbill',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesbill',
            name='quantity',
        ),
        migrations.CreateModel(
            name='PurchaseBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(choices=[('EG', 'Egypt'), ('AE', 'UAE'), ('TR', 'Turkey')], max_length=2)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.purchasebill')),
            ],
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='products',
            field=models.ManyToManyField(through='app.PurchaseBillItem', to='app.product'),
        ),
        migrations.CreateModel(
            name='SalesBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('sales_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.salesbill')),
            ],
        ),
        migrations.AddField(
            model_name='salesbill',
            name='products',
            field=models.ManyToManyField(through='app.SalesBillItem', to='app.product'),
        ),
    ]
