# Generated by Django 5.1 on 2024-09-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_purchasebill_name_salesbill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbillitem',
            name='location',
            field=models.CharField(choices=[('EG', 'Egypt'), ('AE', 'UAE'), ('TR', 'Turkey')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
