# Generated by Django 5.1 on 2024-09-02 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_salesbillitem_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('EGP', 'EGP'), ('TR', 'TR'), ('RS', 'RS'), ('AE', 'AE'), ('STR', 'STR')], max_length=3)),
                ('discount', models.FloatField(default=0)),
                ('location', models.CharField(choices=[('EG', 'Egypt'), ('AE', 'UAE'), ('TR', 'Turkey')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('location', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('product_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.productbill')),
            ],
        ),
    ]
