# Generated by Django 5.1 on 2024-09-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_ahmed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ahmed',
        ),
    ]
