# Generated by Django 5.1 on 2024-09-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_delete_ahmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbillitem',
            name='product_bill',
        ),
        migrations.RemoveField(
            model_name='productbillitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductBill',
        ),
        migrations.DeleteModel(
            name='ProductBillItem',
        ),
    ]
