# Generated by Django 5.1 on 2024-09-03 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_productbill_productbillitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='productspesfication',
            name='name',
        ),
        migrations.AlterField(
            model_name='productspesfication',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='app.product'),
        ),
        migrations.AddField(
            model_name='productspesfication',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.specification'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='specifications',
            field=models.ManyToManyField(blank=True, null=True, related_name='subcategories', to='app.specification'),
        ),
    ]
