# Generated by Django 5.1 on 2024-09-05 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_specification_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategorySpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.specification')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategory')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subcategory', 'specification'), name='unique_specification_for_subcategory')],
            },
        ),
    ]
