# Generated by Django 5.1 on 2024-09-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_subcategoryspecification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategorySpecification',
        ),
    ]
