# Generated by Django 5.1 on 2024-09-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_customer_productbill_customer_salesbill_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbill',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
