# Generated by Django 5.1 on 2024-09-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_productbill_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='eur_to_ae',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='eur_to_egp',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='eur_to_rs',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='eur_to_strlini',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='eur_to_tr',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='eur_to_usd',
        ),
    ]
