# Generated by Django 5.1 on 2024-09-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_productbill_status_salesbill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbillitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
