# Generated by Django 5.1 on 2024-09-09 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_salesbillitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbillitem',
            name='sales_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.salesbill'),
        ),
    ]
