# Generated by Django 5.1 on 2024-09-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_trader_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspesfication',
            name='value',
            field=models.CharField(default='xxx', max_length=255),
        ),
    ]
